jobs:
  create-folder:
    name: Create project folder
    steps:
      - RUN: npx mkdirp ${PROJECT_PATH}
  init-project:
    name: Initialize package.json
    steps:
      - WORKDIR: ${PROJECT_PATH}
      - RUN: npm init -y
  add-typescript:
    name: Configuring TypeScript
    steps:
      - RUN: yarn add -D typescript ts-node-dev @types/node
      - MERGE_JSON: ./templates/package.json ./package.json
      - COPY: ./templates/src ./src